### ISSUE TITLE
panicked with `test.h`, but ok with `__binding.i`

### ISSUE THREAD

**Issue by isghe** [rust-lang/rust-bindgen#1471]
### Input C/C++ Header

```C++
#include <stdint.h>
const uint32_t test = 123;
```

### Bindgen Invocation

```
$ bindgen test.h
```

### Actual Results

```
test.h:5:7: error: unknown type name 'uint32_t'
test.h:5:7: error: unknown type name 'uint32_t', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### Expected Results

generating `__binding.i` file instead it works:

First generate `__binding.i` file using `-dump-preprocessed-input`
```
$ bindgen --dump-preprocessed-input test.h
test.h:2:7: error: unknown type name 'uint32_t'
test.h:2:7: error: unknown type name 'uint32_t', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:1009:5
```

and than:

```
$ bindgen __bindgen.i
warning: argument unused during compilation: '-isystem /usr/local/include' [-Wunused-command-line-argument], err: false
warning: argument unused during compilation: '-isystem /usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include' [-Wunused-command-line-argument], err: false
warning: argument unused during compilation: '-isystem /System/Library/Frameworks' [-Wunused-command-line-argument], err: false
warning: argument unused during compilation: '-isystem /Library/Frameworks' [-Wunused-command-line-argument], err: false
/* automatically generated by rust-bindgen */

pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub const test: u32 = 123;
```
thanks

```
$ bindgen --version
bindgen 0.45.0
$ uname -a
Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```

**Comment by emilio** [comment]
Hmm, that really makes no sense :)

Does `clang test.h` say something interesting?

**Comment by isghe** [comment]
> Hmm, that really makes no sense :)
> 
> Does `clang test.h` say something interesting?
Just no output
```
$ clang test.h
```

**Comment by emilio** [comment]
Is there any chance you could do a debug build and paste here the first lines of the `RUST_LOG=bindgen ./target/debug/bindgen test.h >log 2>&1` in both cases? I suspect clang-sys is finding some bogus includes.

**Comment by emilio** [comment]
Also, does passing `-- -target=<whatever-the-default-macos-target-is>` help?

**Comment by isghe** [comment]
```
$ RUST_LOG=bindgen ./target/debug/bindgen test.h >log 2>&1
$ cat log 
[2018-12-23T17:28:22Z INFO  bindgen] Clang Version: clang version 3.9.0 
[2018-12-23T17:28:22Z DEBUG bindgen] Trying to find clang with flags: []
[2018-12-23T17:28:23Z DEBUG bindgen] Found clang: Clang { path: "/usr/local/bin/clang-3.7", version: Some(CXVersion { Major: 3, Minor: 7, Subminor: 1 }), c_search_paths: Some(["/usr/local/include", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "/System/Library/Frameworks", "/Library/Frameworks"]), cpp_search_paths: Some(["/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../include/c++/v1", "/usr/local/include", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "/System/Library/Frameworks", "/Library/Frameworks"]) }
[2018-12-23T17:28:23Z DEBUG bindgen] Fixed-up options: BindgenOptions { blacklisted_types: RegexSet { items: [], set: Some(RegexSet([])) }, blacklisted_functions: RegexSet { items: [], set: Some(RegexSet([])) }, blacklisted_items: RegexSet { items: [], set: Some(RegexSet([])) }, opaque_types: RegexSet { items: [], set: Some(RegexSet([])) }, rustfmt_path: None, whitelisted_types: RegexSet { items: [], set: Some(RegexSet([])) }, whitelisted_functions: RegexSet { items: [], set: Some(RegexSet([])) }, whitelisted_vars: RegexSet { items: [], set: Some(RegexSet([])) }, default_enum_style: Consts, bitfield_enums: RegexSet { items: [], set: Some(RegexSet([])) }, rustified_enums: RegexSet { items: [], set: Some(RegexSet([])) }, constified_enum_modules: RegexSet { items: [], set: Some(RegexSet([])) }, constified_enums: RegexSet { items: [], set: Some(RegexSet([])) }, builtins: false, emit_ast: false, emit_ir: false, emit_ir_graphviz: None, enable_cxx_namespaces: false, enable_function_attribute_detection: false, disable_name_namespacing: false, layout_tests: true, impl_debug: false, impl_partialeq: false, derive_copy: true, derive_debug: true, derive_default: false, derive_hash: false, derive_partialord: false, derive_ord: false, derive_partialeq: false, derive_eq: false, use_core: false, ctypes_prefix: None, time_phases: false, namespaced_constants: true, msvc_mangling: false, convert_floats: true, raw_lines: [], module_lines: {}, clang_args: ["-isystem", "/usr/local/include", "-isystem", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "-isystem", "/System/Library/Frameworks", "-isystem", "/Library/Frameworks", "test.h"], input_header: Some("test.h"), input_unsaved_files: [], parse_callbacks: None, codegen_config: FUNCTIONS | TYPES | VARS | METHODS | CONSTRUCTORS | DESTRUCTORS, conservative_inline_namespaces: false, generate_comments: true, generate_inline_functions: false, whitelist_recursively: true, objc_extern_crate: false, generate_block: false, block_extern_crate: false, enable_mangling: true, prepend_enum_name: true, rust_target: Stable_1_21, rust_features: RustFeatures { untagged_union: true, associated_const: true, builtin_clone_impls: true, repr_align: false, i128_and_u128: false, must_use_function: false, thiscall_abi: false }, rustfmt_bindings: true, rustfmt_configuration_file: None, no_partialeq_types: RegexSet { items: [], set: Some(RegexSet([])) }, no_copy_types: RegexSet { items: [], set: Some(RegexSet([])) }, no_hash_types: RegexSet { items: [], set: Some(RegexSet([])) } }
test.h:2:7: error: unknown type name 'uint32_t'
[2018-12-23T17:28:23Z DEBUG bindgen::ir::context] BindgenContext::add_item(Item { id: ItemId(0), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, parent_id: ItemId(0), kind: Module(Module { name: Some("root"), kind: Normal, children: {} }) }, declaration: None, loc: None
test.h:2:7: error: unknown type name 'uint32_t', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ RUST_LOG=bindgen ./target/debug/bindgen --dump-preprocessed-input test.h >log 2>&1
$ cat log 
[2018-12-23T17:29:42Z INFO  bindgen] Clang Version: clang version 3.9.0 
[2018-12-23T17:29:43Z DEBUG bindgen] Trying to find clang with flags: []
[2018-12-23T17:29:44Z DEBUG bindgen] Found clang: Clang { path: "/usr/local/bin/clang-3.7", version: Some(CXVersion { Major: 3, Minor: 7, Subminor: 1 }), c_search_paths: Some(["/usr/local/include", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "/System/Library/Frameworks", "/Library/Frameworks"]), cpp_search_paths: Some(["/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../include/c++/v1", "/usr/local/include", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "/System/Library/Frameworks", "/Library/Frameworks"]) }
[2018-12-23T17:29:44Z DEBUG bindgen] Fixed-up options: BindgenOptions { blacklisted_types: RegexSet { items: [], set: Some(RegexSet([])) }, blacklisted_functions: RegexSet { items: [], set: Some(RegexSet([])) }, blacklisted_items: RegexSet { items: [], set: Some(RegexSet([])) }, opaque_types: RegexSet { items: [], set: Some(RegexSet([])) }, rustfmt_path: None, whitelisted_types: RegexSet { items: [], set: Some(RegexSet([])) }, whitelisted_functions: RegexSet { items: [], set: Some(RegexSet([])) }, whitelisted_vars: RegexSet { items: [], set: Some(RegexSet([])) }, default_enum_style: Consts, bitfield_enums: RegexSet { items: [], set: Some(RegexSet([])) }, rustified_enums: RegexSet { items: [], set: Some(RegexSet([])) }, constified_enum_modules: RegexSet { items: [], set: Some(RegexSet([])) }, constified_enums: RegexSet { items: [], set: Some(RegexSet([])) }, builtins: false, emit_ast: false, emit_ir: false, emit_ir_graphviz: None, enable_cxx_namespaces: false, enable_function_attribute_detection: false, disable_name_namespacing: false, layout_tests: true, impl_debug: false, impl_partialeq: false, derive_copy: true, derive_debug: true, derive_default: false, derive_hash: false, derive_partialord: false, derive_ord: false, derive_partialeq: false, derive_eq: false, use_core: false, ctypes_prefix: None, time_phases: false, namespaced_constants: true, msvc_mangling: false, convert_floats: true, raw_lines: [], module_lines: {}, clang_args: ["-isystem", "/usr/local/include", "-isystem", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "-isystem", "/System/Library/Frameworks", "-isystem", "/Library/Frameworks", "test.h"], input_header: Some("test.h"), input_unsaved_files: [], parse_callbacks: None, codegen_config: FUNCTIONS | TYPES | VARS | METHODS | CONSTRUCTORS | DESTRUCTORS, conservative_inline_namespaces: false, generate_comments: true, generate_inline_functions: false, whitelist_recursively: true, objc_extern_crate: false, generate_block: false, block_extern_crate: false, enable_mangling: true, prepend_enum_name: true, rust_target: Stable_1_21, rust_features: RustFeatures { untagged_union: true, associated_const: true, builtin_clone_impls: true, repr_align: false, i128_and_u128: false, must_use_function: false, thiscall_abi: false }, rustfmt_bindings: true, rustfmt_configuration_file: None, no_partialeq_types: RegexSet { items: [], set: Some(RegexSet([])) }, no_copy_types: RegexSet { items: [], set: Some(RegexSet([])) }, no_hash_types: RegexSet { items: [], set: Some(RegexSet([])) } }
test.h:2:7: error: unknown type name 'uint32_t'
[2018-12-23T17:29:44Z DEBUG bindgen::ir::context] BindgenContext::add_item(Item { id: ItemId(0), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, parent_id: ItemId(0), kind: Module(Module { name: Some("root"), kind: Normal, children: {} }) }, declaration: None, loc: None
test.h:2:7: error: unknown type name 'uint32_t', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ RUST_LOG=bindgen ./target/debug/bindgen __bindgen.i >log.i 2>&1
$ cat log.i
[2018-12-23T17:30:23Z INFO  bindgen] Clang Version: clang version 3.9.0 
[2018-12-23T17:30:23Z DEBUG bindgen] Trying to find clang with flags: []
[2018-12-23T17:30:24Z DEBUG bindgen] Found clang: Clang { path: "/usr/local/bin/clang-3.7", version: Some(CXVersion { Major: 3, Minor: 7, Subminor: 1 }), c_search_paths: Some(["/usr/local/include", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "/System/Library/Frameworks", "/Library/Frameworks"]), cpp_search_paths: Some(["/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../include/c++/v1", "/usr/local/include", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "/System/Library/Frameworks", "/Library/Frameworks"]) }
[2018-12-23T17:30:24Z DEBUG bindgen] Fixed-up options: BindgenOptions { blacklisted_types: RegexSet { items: [], set: Some(RegexSet([])) }, blacklisted_functions: RegexSet { items: [], set: Some(RegexSet([])) }, blacklisted_items: RegexSet { items: [], set: Some(RegexSet([])) }, opaque_types: RegexSet { items: [], set: Some(RegexSet([])) }, rustfmt_path: None, whitelisted_types: RegexSet { items: [], set: Some(RegexSet([])) }, whitelisted_functions: RegexSet { items: [], set: Some(RegexSet([])) }, whitelisted_vars: RegexSet { items: [], set: Some(RegexSet([])) }, default_enum_style: Consts, bitfield_enums: RegexSet { items: [], set: Some(RegexSet([])) }, rustified_enums: RegexSet { items: [], set: Some(RegexSet([])) }, constified_enum_modules: RegexSet { items: [], set: Some(RegexSet([])) }, constified_enums: RegexSet { items: [], set: Some(RegexSet([])) }, builtins: false, emit_ast: false, emit_ir: false, emit_ir_graphviz: None, enable_cxx_namespaces: false, enable_function_attribute_detection: false, disable_name_namespacing: false, layout_tests: true, impl_debug: false, impl_partialeq: false, derive_copy: true, derive_debug: true, derive_default: false, derive_hash: false, derive_partialord: false, derive_ord: false, derive_partialeq: false, derive_eq: false, use_core: false, ctypes_prefix: None, time_phases: false, namespaced_constants: true, msvc_mangling: false, convert_floats: true, raw_lines: [], module_lines: {}, clang_args: ["-isystem", "/usr/local/include", "-isystem", "/usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include", "-isystem", "/System/Library/Frameworks", "-isystem", "/Library/Frameworks", "__bindgen.i"], input_header: Some("__bindgen.i"), input_unsaved_files: [], parse_callbacks: None, codegen_config: FUNCTIONS | TYPES | VARS | METHODS | CONSTRUCTORS | DESTRUCTORS, conservative_inline_namespaces: false, generate_comments: true, generate_inline_functions: false, whitelist_recursively: true, objc_extern_crate: false, generate_block: false, block_extern_crate: false, enable_mangling: true, prepend_enum_name: true, rust_target: Stable_1_21, rust_features: RustFeatures { untagged_union: true, associated_const: true, builtin_clone_impls: true, repr_align: false, i128_and_u128: false, must_use_function: false, thiscall_abi: false }, rustfmt_bindings: true, rustfmt_configuration_file: None, no_partialeq_types: RegexSet { items: [], set: Some(RegexSet([])) }, no_copy_types: RegexSet { items: [], set: Some(RegexSet([])) }, no_hash_types: RegexSet { items: [], set: Some(RegexSet([])) } }
[2018-12-23T17:30:24Z DEBUG bindgen::ir::context] BindgenContext::add_item(Item { id: ItemId(0), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None, constify_enum_variant: false, derives: [] }, parent_id: ItemId(0), kind: Module(Module { name: Some("root"), kind: Normal, children: {} }) }, declaration: None, loc: None
warning: argument unused during compilation: '-isystem /usr/local/include' [-Wunused-command-line-argument], err: false
warning: argument unused during compilation: '-isystem /usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include' [-Wunused-command-line-argument], err: false
warning: argument unused during compilation: '-isystem /System/Library/Frameworks' [-Wunused-command-line-argument], err: false
warning: argument unused during compilation: '-isystem /Library/Frameworks' [-Wunused-command-line-argument], err: false
[2018-12-23T17:30:24Z DEBUG bindgen::ir::item] Item::from_ty_with_id: ItemId(1)
	ty = Type(int64_t, kind: Typedef, cconv: 100, decl: Cursor(int64_t kind: TypedefDecl, loc: __bindgen.i:72:23, usr: Some("c:@T@int64_t")), canon: Cursor(int64_t kind: TypedefDecl, loc: __bindgen.i:72:23, usr: Some("c:@T@int64_t"))),

{…omissis…}

Warning: Unknown configuration option `fn_brace_style`
Warning: Unknown configuration option `item_brace_style`
Warning: Unknown configuration option `struct_lit_multiline_style`
Warning: Unknown configuration option `where_trailing_comma`
/* automatically generated by rust-bindgen */

pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub const test: u32 = 123;
```

**Comment by emilio** [comment]
Hmm, there seems to be something messed up in your setup, we're picking clang 3.7, but loading a libclang version 3.9... That's extremely weird.

**Comment by isghe** [comment]
> Hmm, there seems to be something messed up in your setup, we're picking clang 3.7, but loading a libclang version 3.9... That's extremely weird.

I'll investigate on this; anyway I would like to have the same result: both failure, or both success, not a mix.
It's weird, I agree.

**Comment by emilio** [comment]
Yeah, I agree, but if that unit test is not run on your particular setup it is not really useful. Let me know if you find out what's weird about the setup and I can help trying to set up a test for it / fix it.
