### ISSUE TITLE
binding GNU Scientific Library : file not found

### ISSUE THREAD

**Issue by Anthomedal** [rust-lang/rust-bindgen#1759]
Hello everyone ! I want to bind the GNU Scientific Library ([https://www.gnu.org/software/gsl/](url)) (I know the crate [https://crates.io/crates/GSL](url) but I want to be able to modify this library before use).

### Input C/C++ Header
You can see full code here : [https://github.com/Anthomedal/GSL_bindgen_issue](url), just focus on gsl folder (the github contain compiled library for my OS). I add the wrapper rust_wrapper.h and I want to bind it. First, I changes the
`#include <gsl/something.h>` 

into 
`#include "gsl/something.h"`

(everywhere in headers) because I've seen how problematic it can be. 
### Bindgen Invocation
I tried with command line tool : 
`bindgen ./rust_wrapper.h -o ./bind.rs`

### Actual Results
```
./gsl/gsl_permute_matrix_float.h:24:10: fatal error: 'gsl/gsl_errno.h' file not found
./gsl/gsl_permute_matrix_float.h:24:10: fatal error: 'gsl/gsl_errno.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /home/anthony/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/main.rs:56:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  16: bindgen::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start

```

### System 
Linux Mint Debian Edition 3

### Attempts
I tried with clang 3.8, 3.9 and 4.0. I didn't try other flags.

Can somebody help me ? I'm sorry for the C code size but this is my problem. 
Thank you !

**Comment by emilio** [comment]
> You can see full code here : https://github.com/Anthomedal/GSL_bindgen_issue, just focus on gsl folder (the github contain compiled library for my OS). I add the wrapper rust_wrapper.h and I want to bind it. First, I changes the

That link is not reachable?

But generally there should be no issue with `<` includes and such. Pass `-I` in the clang flags maybe?

**Comment by Anthomedal** [comment]
I'm sorry, now this repo is public. I tried this : 
```

$ RUST_BACKTRACE=1 bindgen ./rust_wrapper.h -o ./bind.rs -- -I
warning: /usr/local/include: 'linker' input unused [-Wunused-command-line-argument]
./gsl/gsl_permute_matrix_float.h:24:10: fatal error: 'gsl/gsl_errno.h' file not found
warning: /usr/local/include: 'linker' input unused [-Wunused-command-line-argument], err: false
./gsl/gsl_permute_matrix_float.h:24:10: fatal error: 'gsl/gsl_errno.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /home/anthony/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/main.rs:56:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  16: bindgen::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

and 
```

$ RUST_BACKTRACE=1 bindgen ./rust_wrapper.h -o ./bind.rs -- -I./gsl/
./gsl/gsl_permute_matrix_float.h:24:10: fatal error: 'gsl/gsl_errno.h' file not found
./gsl/gsl_permute_matrix_float.h:24:10: fatal error: 'gsl/gsl_errno.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /home/anthony/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/main.rs:56:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  16: bindgen::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by Anthomedal** [comment]
Sorry : that's work ! 

Solution : `bindgen ./rust_wrapper.h -o ./bind.rs -- -I./`

Thank you very much !
