### ISSUE TITLE
libclang build error

### ISSUE THREAD

**Issue by protonesso** [rust-lang/rust-bindgen#1867]
Hello, I'm building Mozilla Thunderbird from source, all targets passed except bindgen, here's the error message:
 ```
15:28.48 thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.10 could not be opened: Dynamic loading not supported"', /usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/third_party/rust/bindgen/src/lib.rs:1956:13
```
My toolchain is musl 1.2.1, gcc 10.2.0, clang 10.0.1 (with all headers, static and dynamic libraries installed), rust 1.45.2 (for x86_64-unknown-linux-musl, directly from rustup)

**Comment by emilio** [comment]
Do you have a more expanded error message somewhere? That error seems to come from deep in your system.

bindgen is dynamically linking to libclang, which seems like it's somehow erroring (even though there's a dynamic library).

**Comment by protonesso** [comment]
More options of debug?

**Comment by protonesso** [comment]
Full log:
```
 2:11.44 error: failed to run custom build command for `neqo-crypto v0.2.4 (https://github.com/mozilla/neqo?tag=v0.2.4#6fca78d0)`
 2:11.44 Caused by:
 2:11.44   process didn't exit successfully: `/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/neqo-crypto-3592685fede87918/build-script-build` (exit code: 101)
 2:11.44 --- stdout
 2:11.44 cargo:rustc-link-lib=dylib=nssutil3
 2:11.44 cargo:rustc-link-lib=dylib=nss3
 2:11.44 cargo:rustc-link-lib=dylib=ssl3
 2:11.44 cargo:rustc-link-lib=dylib=plds4
 2:11.44 cargo:rustc-link-lib=dylib=plc4
 2:11.44 cargo:rustc-link-lib=dylib=nspr4
 2:11.44 cargo:rustc-link-search=native=/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/dist/bin
 2:11.44 cargo:rustc-link-search=native=/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/security/nss/lib/nss/nss_nss3
 2:11.44 cargo:rustc-link-search=native=/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/security/nss/lib/ssl/ssl_ssl3
 2:11.44 cargo:rustc-link-search=native=/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/config/external/nspr/pr
 2:11.44 cargo:rerun-if-changed=/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/netwerk/socket/neqo/extra-bindgen-flags
 2:11.44 cargo:rerun-if-changed=bindings/bindings.toml
 2:11.44 cargo:rerun-if-changed=bindings/nss_secerr.h
 2:11.45 --- stderr
 2:11.45 thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.10 could not be opened: Dynamic loading not supported"', /usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/third_party/rust/bindgen/src/lib.rs:1956:13
 2:11.45 stack backtrace:
 2:11.45    0:           0x5b9e35 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd93944e1acd02cf2
 2:11.45    1:           0x5f64bc - core::fmt::write::h5922fc05561b967b
 2:11.45    2:           0x5b66c3 - std::io::Write::write_fmt::h34b3880ef2e08108
 2:11.45    3:           0x5bc7e0 - std::panicking::default_hook::{{closure}}::hdab7fee73142707b
 2:11.45    4:           0x5bc52c - std::panicking::default_hook::hc49cbef9c34e97c4
 2:11.45    5:           0x5bce17 - std::panicking::rust_panic_with_hook::h54ee2e16431d9887
 2:11.45    6:           0x5bca1b - rust_begin_unwind
 2:11.45    7:           0x5f4e21 - core::panicking::panic_fmt::hc1c2c5ab6998e83b
 2:11.45    8:           0x5f4c43 - core::result::unwrap_failed::h2306e8440c006cc6
 2:11.45    9:           0x4214b1 - std::sync::once::Once::call_once::{{closure}}::hc408def9f9cadbae
 2:11.45   10:           0x5b97fb - std::sync::once::Once::call_inner::h089b9c5108b0b387
 2:11.45   11:           0x429fb7 - bindgen::Builder::generate::ha02ac871ec12467e
 2:11.45   12:           0x41406b - build_script_build::main::h3661fe2caa9186a5
 2:11.45   13:           0x4175a3 - std::rt::lang_start::{{closure}}::h7dd632ff687dee36
 2:11.45   14:           0x5bd191 - std::rt::lang_start_internal::he5b928765d81cbd0
 2:11.45   15:           0x414a02 - main
 2:11.45 warning: build failed, waiting for other jobs to finish...
 2:18.48 error: linking with `/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/build/cargo-linker` failed: exit code: 1
 2:18.48   |
 2:18.48   = note: "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/build/cargo-linker" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-m64" "-nostartfiles" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/crt1.o" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/crti.o" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.0.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.1.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.10.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.11.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.12.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.13.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.14.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.15.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.2.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.3.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.4.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.5.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.6.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.7.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.8.rcgu.o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.build_script_build.6uf3z7wt-cgu.9.rcgu.o" "-o" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3.3kqya3kmv85q35uq.rcgu.o" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps" "-L" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/glslopt-953fa8837085b978/out" "-L" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/glslopt-953fa8837085b978/out" "-L" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/glslopt-953fa8837085b978/out" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libglslopt-15fc8e57e81959bf.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libbuild_parallel-cee9c55ac827d6c0.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libnum_cpus-6c28bfa3634f9d4a.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libjobserver-51a380e780cb7609.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/liblibc-ac1b1a981803a84d.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libcrossbeam_utils-2d1ab63fb2981b2e.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libcfg_if-6f7b4dc60955c66b.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libwebrender_build-ee052d83dfce9f8a.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libserde-5bdc6b8e73759c3f.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/liblazy_static-294aef31f007904e.rlib" "/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libbitflags-8cb73975d6a4abc4.rlib" "-Wl,--start-group" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-6d58bc9e45052f27.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-d2218d0a05f2afa4.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-e4fbfa7f0925f555.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-45e930b3f2c7be7a.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace-4b06cfc5dc3a204d.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace_sys-7b6eb6aba8256c00.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-b6f9554cef162dd4.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libunwind-3cb00da2592899c7.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-9dcf53fe1317e1fd.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-10941a21a88666ce.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-b852c17779cb8fc7.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-69c2a9e8ef492771.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-6914d93bde38d1ce.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-24e199ab374497dd.rlib" "-Wl,-Bdynamic" "-lstdc++" "/usr/lib/rustlib/x86_64-unknown-linux-musl/lib/crtn.o"
 2:18.48   = note: clang-10: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
 2:18.48           /usr/bin/ld: attempted static link of dynamic object `/usr/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../libstdc++.so'
 2:18.48           /usr/bin/ld: /usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libglslopt-15fc8e57e81959bf.rlib(glsl_types.o): in function `_GLOBAL__sub_I_glsl_types.cpp':
 2:18.48           glsl_types.cpp:(.text.startup+0x44): undefined reference to `__dso_handle'
 2:18.48           /usr/bin/ld: glsl_types.cpp:(.text.startup+0x1a26): undefined reference to `__dso_handle'
 2:18.48           /usr/bin/ld: glsl_types.cpp:(.text.startup+0x1a98): undefined reference to `__dso_handle'
 2:18.48           /usr/bin/ld: glsl_types.cpp:(.text.startup+0x1b10): undefined reference to `__dso_handle'
 2:18.48           /usr/bin/ld: glsl_types.cpp:(.text.startup+0x1b82): undefined reference to `__dso_handle'
 2:18.48           /usr/bin/ld: /usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/deps/libglslopt-15fc8e57e81959bf.rlib(glsl_types.o):glsl_types.cpp:(.text.startup+0x1bfa): more undefined references to `__dso_handle' follow
 2:18.48           /usr/bin/ld: /usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/obj-x86_64-pc-linux-musl/release/build/webrender-4d2b43d0a670b0e3/build_script_build-4d2b43d0a670b0e3: hidden symbol `__dso_handle' isn't defined
 2:18.48           /usr/bin/ld: final link failed: bad value
 2:18.49           clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
 2:18.49           
 2:18.63 error: aborting due to previous error
 2:52.61 error: build failed
 2:52.61 gmake[4]: *** [/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/config/makefiles/rust.mk:298: force-cargo-library-build] Error 101
 2:52.61 gmake[3]: *** [/usr/ports/packages/thunderbird/work/src/thunderbird-78.1.1/config/recurse.mk:74: toolkit/library/rust/target] Error 2
 2:52.61 gmake[3]: *** Waiting for unfinished jobs....
```

**Comment by emilio** [comment]
Can you run bindgen standalone? As in `git clone` this repo, `cargo build`, then `./target/debug/bindgen <some-header>`?

**Comment by protonesso** [comment]
Will try tomorrow then

**Comment by 12101111** [comment]
> Can you run bindgen standalone? As in `git clone` this repo, `cargo build`, then `./target/debug/bindgen <some-header>`?

standalone bindgen gave same error:

```
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/llvm/10/lib/libclang.so.10 could not be opened: Dynamic loading not supported"', src/lib.rs:1896:31
```

**Comment by emilio** [comment]
Ok, I think this is not something fixable in bindgen itself (you could maybe use the `static` feature from `bindgen` to get the behavior you want, though that involves changing the bindgen-related `features = ["runtime"]` by `features = ["static"]` [here](https://searchfox.org/mozilla-central/search?q=features+%3D+%5B%22runtime%22&path=&case=false&regexp=false)).

Though let me know if that's not sufficient or we could improve it somehow. Thanks for the comment @12101111!

**Comment by protonesso** [comment]
The problem was crt-static btw

сб, 15 авг. 2020 г., 14:54 Emilio Cobos Álvarez <notifications@github.com>:

**Comment by yshui** [comment]
@12101111 `RUSTFLAGS=-Ctarget-feature=-crt-static` won't work for build-dependencies, see rust-lang/cargo#4423

**Comment by yshui** [comment]
I hit this problem compiling firefox. It's difficult to patch firefox to have `features = ["static"]` for everything that depends on bindgen. I wonder if there is a better way.
