### ISSUE TITLE
fatal error: 'stdlib.h' file not found when including cstdlib header

### ISSUE THREAD

**Issue by doppioandante** [rust-lang/rust-bindgen#1919]
There are similar issues (e.g. #1521) but I can't understand how to fix this. I don't think this is a bindgen issue, but can't unterstand what underlying component is causing this. My system is Ubuntu 20.10, with llvm & co installed.

Repro: Modify https://github.com/fitzgen/bindgen-tutorial-bzip2-sys.git like this:

rename `wrapper.h` to `wrapper.hpp`

`wrapper.hpp`
```C++
#include <bzlip.h>
#include <cstdlib>
```
and modify `build.rs`:

```Rust
    println!("cargo:rustc-link-lib=bz2");

    let bindings = bindgen::Builder::default()
        .header("wrapper.hpp")
        .whitelist_type("bz_stream")
        .generate()
        .expect("Unable to generate bindings");

```

The bzip.h include is useless but I wanted to start from a basilar working repo.
Substituting `#include <cstdlib>` with `#include <stdlib.h>` makes bindgen happy.

### `cargo build` result

```
$ RUST_BACKTRACE=1 cargo build
   Compiling bindgen-tutorial-bzip2-sys v0.1.0 (/home/enrico/projects/misc/bindgen-tutorial-bzip2-sys)
error: failed to run custom build command for `bindgen-tutorial-bzip2-sys v0.1.0 (/home/enrico/projects/misc/bindgen-tutorial-bzip2-sys)`

Caused by:
  process didn't exit successfully: `/home/enrico/projects/misc/bindgen-tutorial-bzip2-sys/target/debug/build/bindgen-tutorial-bzip2-sys-345f7e1f733377eb/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=bz2

  --- stderr
  /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/cstdlib:75:15: fatal error: 'stdlib.h' file not found
  /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/cstdlib:75:15: fatal error: 'stdlib.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:13:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
     1: core::panicking::panic_fmt
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
     2: core::option::expect_none_failed
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
     3: core::result::Result<T,E>::expect
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:933
     4: build_script_build::main
               at ./build.rs:9
     5: core::ops::function::FnOnce::call_once
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by emilio** [comment]
`<cstdlib.h>` is not a valid header. If you're building in C mode you need `<stdlib.h>`, if you're building in  C++ mode you need `<cstdlib>` (note: no `.h`).

That header doesn't compile in a regular C compiler either, so I think the behavior here is right, but please reopen if I've missed something.

**Comment by doppioandante** [comment]
I'm sorry, I obviously mistyped. The repro file correctly has "<cstdlib>" and I edited the initial post. Could you please reopen @emilio?

**Comment by emilio** [comment]
Ah, I see what's going on... Right now bindgen assumes C input unless `-x c++` is specified (or similar).

I opened https://github.com/rust-lang/rust-bindgen/pull/1933 to also look at the filename.
