### ISSUE TITLE
Panic resolving typerefs

### ISSUE THREAD

**Issue by adetaylor** [rust-lang/rust-bindgen#2039]
### Input C/C++ Header

```C++
namespace {
namespace {
namespace {
template <typename a> class b {
public:
  operator a *() { c; }
  static __thread a *c;
};
template <typename a> __thread a *b<a>::c;
template <typename a> class d : public b<a> {};
template <typename e, typename f> class g {
public:
  class context {
  public:
    context();
    e c;
  };
  static f *contains() {
    context *elem = h;
    elem->c;
  }
  static d<context> h;
};
class i;
class j {
public:
  typedef g<j, i> k;
};
class l : j {
  ~l();
};
l::~l() { k::contains; }
} // namespace
} // namespace
} // namespace
```

### Bindgen Invocation

```RUST_BACKTRACE=1 cargo run /Users/adetaylor/reduced-fiddle/minimized.hpp```

### Actual Results

```
$ RUST_BACKTRACE=1 cargo run /Users/adetaylor/reduced-fiddle/minimized.hpp 
   Compiling bindgen v0.58.1 (/Users/adetaylor/dev/bindgen)
    Finished dev [unoptimized + debuginfo] target(s) in 4.95s
     Running `target/debug/bindgen /Users/adetaylor/reduced-fiddle/minimized.hpp`
/Users/adetaylor/reduced-fiddle/minimized.hpp:32:11: warning: expression result unused [-Wunused-value], err: false
/Users/adetaylor/reduced-fiddle/minimized.hpp:20:11: warning: expression result unused [-Wunused-value], err: false
/Users/adetaylor/reduced-fiddle/minimized.hpp:21:3: warning: non-void function does not return a value [-Wreturn-type], err: false
/Users/adetaylor/reduced-fiddle/minimized.hpp:19:21: warning: instantiation of variable '(anonymous namespace)::(anonymous namespace)::(anonymous namespace)::g<(anonymous namespace)::(anonymous namespace)::(anonymous namespace)::j, (anonymous namespace)::(anonymous namespace)::(anonymous namespace)::i>::h' required here, but no definition is available [-Wundefined-var-template], err: false
/Users/adetaylor/reduced-fiddle/minimized.hpp:6:20: warning: expression result unused [-Wunused-value], err: false
/Users/adetaylor/reduced-fiddle/minimized.hpp:6:23: warning: non-void function does not return a value [-Wreturn-type], err: false
/Users/adetaylor/reduced-fiddle/minimized.hpp:22:21: warning: variable '(anonymous namespace)::(anonymous namespace)::(anonymous namespace)::g<(anonymous namespace)::(anonymous namespace)::(anonymous namespace)::j, (anonymous namespace)::(anonymous namespace)::(anonymous namespace)::i>::h' has internal linkage but is not defined [-Wundefined-internal], err: false
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(TypeId(ItemId(50)))`,
 right: `None`', src/ir/context.rs:721:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/392ba2ba1a7d6c542d2459fb8133bebf62a4a423/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/392ba2ba1a7d6c542d2459fb8133bebf62a4a423/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
             at /rustc/392ba2ba1a7d6c542d2459fb8133bebf62a4a423/library/core/src/panicking.rs:160:17
   3: core::panicking::assert_failed
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:117:5
   4: bindgen::ir::context::BindgenContext::add_item
             at ./src/ir/context.rs:721:13
   5: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id
             at ./src/ir/item.rs:1636:17
   6: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty
             at ./src/ir/item.rs:1522:9
   7: bindgen::ir::context::BindgenContext::resolve_typerefs
             at ./src/ir/context.rs:901:36
   8: bindgen::ir::context::BindgenContext::gen
             at ./src/ir/context.rs:1134:9
   9: bindgen::codegen::codegen
             at ./src/codegen/mod.rs:4184:5
  10: bindgen::Bindings::generate
             at ./src/lib.rs:2289:32
  11: bindgen::Builder::generate
             at ./src/lib.rs:1434:9
  12: bindgen::main::{{closure}}
             at ./src/main.rs:54:17
  13: std::panicking::try::do_call
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  14: ___rust_try
  15: std::panicking::try
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  16: std::panic::catch_unwind
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  17: bindgen::main
             at ./src/main.rs:53:34
  18: core::ops::function::FnOnce::call_once
             at /Users/adetaylor/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected Results

Unclear. This is a creduced test case, and I haven't dug into what's causing it.

### Notes

These symptoms are a lot like #2036, _but_ this reproduces either with revision c39c47c2e5a3839ab57dec0d585b7e6af60416f6 (master) or c78cc14b05fbc627f64ad5c6644968637760f7cf (@pcwalton's branch from #2037). So I'm reporting it as a separate issue. (The above callstack is from the latter, in case it makes a difference to line numbers),

**Comment by emilio** [comment]
So this looks indeed extremely similar to #2036. We did a few tweaks before merging it but after digging a bit the problem is a bit more subtle.

So, basically, we're parsing something twice (in this case the class declaration with the usr `c:t.hpp@aN@S@g>#$@aN@S@j#$@aN@S@i@S@context`), but `builtin_or_resolved_ty` doesn't know about it (which is what should take care of exiting early in these cases, generally).

So `builtin_or_resolved_ty` tries to find the right declaration by doing `ty.canonical_declaration(location.as_ref())`. But that doesn't cut it. However the declaration we get in `BindgenContext::add_item` does contain the right `ClassDecl`. So we need to make those match, somehow, and then I think we should be good.

If this debug assertion is blocking people and nobody has the cycles to investigate a bit further (I can try, but my bindgen time is unpaid so... :)), it might be reasonable for now to make it an `extra_assert!` for now. It seems that worse case we'd generate a duplicate type that the user could filter out.

**Comment by adetaylor** [comment]
So far as I know it's not blocking - the person who reported it originally switched happily over to release builds :) Thanks for digging into it!

**Comment by thomaseizinger** [comment]
> If this debug assertion is blocking people and nobody has the cycles to investigate a bit further (I can try, but my bindgen time is unpaid so... :)), it might be reasonable for now to make it an `extra_assert!` for now. It seems that worse case we'd generate a duplicate type that the user could filter out.

Hi, original reporter here !

Thank you for looking into this!
It is not blocking at the moment but I'd be happy to give it a crack in solving this issue. From what you wrote, it doesn't sound too hard? I've never contributed to bindgen though so a if you have any more pointers, those would be very appreciated!
