### ISSUE TITLE
Bindings TileDB 2.7.2 gives deprecated warnings and an error on std::byte

### ISSUE THREAD

**Issue by mamscience** [rust-lang/rust-bindgen#2188]
Hello community

Thanks for reading this issue. There is a crate for binding TileDB to rust. But since it's publication, both TileDB and Bindgen improved a bit, so I wanted to make a binding with the latest greatest. Unfortunately, bindgen bucks at the binding part, see the error below.

The error was produced using TileDB version 2.7.2 and bindgen 0.59.2. Using the TileDB version from the earlier crate (2.2.1) doesn't produce this result with the latest version of bindgen. Is there an option I'm missing?

Thanks in advance

### Input C/C++ Header
e.g. type.h 89 & 178
```
#type.h 89 
template <>
struct type_to_tiledb<int8_t> {
  using type = int8_t;
  static const tiledb_datatype_t tiledb_type = TILEDB_INT8;
  static constexpr const char* name = "INT8";
};

#type.h 178
struct tiledb_to_type<TILEDB_UINT8> {
  using type = uint8_t;
  static const tiledb_datatype_t tiledb_type = TILEDB_UINT8;
  static constexpr const char* name = "UINT8";
};

```
e.g. array_schema.h 187 & 154

```
#array_schema.h 187
  ArraySchema(
      const Context& ctx,
      const std::string& uri,
      tiledb_encryption_type_t encryption_type,
      const std::string& encryption_key)
      : ArraySchema(
            ctx,
            uri,
            encryption_type,
            encryption_key.data(),
            (uint32_t)encryption_key.size()) {
  }



#array_schema.h 154

  TILEDB_DEPRECATED
  ArraySchema(
      const Context& ctx,
      const std::string& uri,
      tiledb_encryption_type_t encryption_type,
      const void* encryption_key,
      uint32_t key_length)
      : Schema(ctx) {
    tiledb_ctx_t* c_ctx = ctx.ptr().get();
    tiledb_array_schema_t* schema;
    ctx.handle_error(tiledb_array_schema_load_with_key(
        c_ctx,
        uri.c_str(),
        encryption_type,
        encryption_key,
        key_length,
        &schema));
    schema_ = std::shared_ptr<tiledb_array_schema_t>(schema, deleter_);
  }
```

### Bindgen Invocation

```Rust
let bindings = bindgen::Builder::default()
        // The input header we would like to generate
        // bindings for.
        .header("wrapper.hpp")
        .rustified_enum(".*")
        .generate_inline_functions(true)
        .derive_default(true)
        .clang_args(vec![
            format!("-I{}/dist/include", &out_dir),
            "-std=c++14".to_string(),
        ])
        .enable_cxx_namespaces()
        .opaque_type("std::.*")
        .blocklist_type("int_type")
        .blocklist_type("off_type")
        .allowlist_type("tiledb.*")
        .module_raw_lines(
            "root",
            [
                "pub type int_type = ::std::os::raw::c_int;",
                "pub type off_type = root::std::streamoff;",
            ]
            .iter()
            .map(|s| *s),
        )
        .derive_copy(false)
        .allowlist_function("tiledb.*")
        // Tell cargo to invalidate the built crate whenever any of the
        // included header files changed.
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        // Finish the builder and generate the bindings.
        .generate()

        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
```

### Actual Results

```
 --- stderr
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/type.h:89:28: error: no member named 'byte' in namespace 'std'
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/type.h:178:21: error: no type named 'byte' in namespace 'std'
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array_schema.h:187:9: warning: 'ArraySchema' is deprecated [-Wdeprecated-declarations]
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array_schema.h:154:3: note: 'ArraySchema' has been explicitly marked deprecated here
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:482:5: warning: 'open' is deprecated [-Wdeprecated-declarations]
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:450:3: note: 'open' has been explicitly marked deprecated here
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:581:5: warning: 'open' is deprecated [-Wdeprecated-declarations]
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:546:3: note: 'open' has been explicitly marked deprecated here
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:835:12: warning: 'consolidate' is deprecated [-Wdeprecated-declarations]
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:772:3: note: 'consolidate' has been explicitly marked deprecated here
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:970:12: warning: 'create' is deprecated [-Wdeprecated-declarations]
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:934:3: note: 'create' has been explicitly marked deprecated here
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:1335:5: warning: 'consolidate' is deprecated [-Wdeprecated-declarations]
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:772:3: note: 'consolidate' has been explicitly marked deprecated here
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/type.h:89:28: error: no member named 'byte' in namespace 'std', err: true
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/type.h:178:21: error: no type named 'byte' in namespace 'std', err: true
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array_schema.h:187:9: warning: 'ArraySchema' is deprecated [-Wdeprecated-declarations], err: false
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:482:5: warning: 'open' is deprecated [-Wdeprecated-declarations], err: false
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:581:5: warning: 'open' is deprecated [-Wdeprecated-declarations], err: false
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:835:12: warning: 'consolidate' is deprecated [-Wdeprecated-declarations], err: false
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:970:12: warning: 'create' is deprecated [-Wdeprecated-declarations], err: false
/project/target/debug/build/tiledb-rust-df5d5c6616bd44f7/out/dist/include/tiledb/array.h:1335:5: warning: 'consolidate' is deprecated [-Wdeprecated-declarations], err: false
 thread 'main' panicked at 'Unable to generate bindings: ()', tiledb-rust/build.rs:90:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
     2: core::result::unwrap_failed
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1617:5
     3: core::result::Result<T,E>::expect
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1259:23
     4: build_script_build::main
               at ./build.rs:56:20
     5: core::ops::function::FnOnce::call_once
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

### Expected Results

Expected to handle deprecated code? And what about byte?

**Comment by emilio** [comment]
Those errors come directly from clang. It seems the library is using std::byte which needs C++17: https://en.cppreference.com/w/cpp/types/byte

So I expect passing the right flags would do.
