### ISSUE TITLE
Binding headers with angled includes

### ISSUE THREAD

**Issue by EbonJaeger** [rust-lang/rust-bindgen#2217]
Hello,

This is more of a question than an issue. I'm trying to generate rust bindings for the plugin/applet library for Budgie Desktop. I can't figure out how to generate the bindings for the plugin header; the `#includes` in that header use angled includes for the other files in that directory, and `bindgen` seems to not like that. Is there any way around that besides changing the header file?

### Input C/C++ Header

```C
#include <budgie-desktop/applet.h>
#include <budgie-desktop/plugin.h>
```

The `plugin.h` header can be found [here](https://github.com/BuddiesOfBudgie/budgie-desktop/blob/master/src/plugin/plugin.h).

### Bindgen Invocation

```Rust
bindgen::Builder::default()
        // The input header we would like to generate
        // bindings for.
        .header("wrapper.h")
        // Tell cargo to invalidate the built crate whenever any of the
        // included header files changed.
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        // Add the dependencies to the include path
        .clang_args([
            "-I",
            "/usr/include/glib-2.0",
            "-I",
            "/usr/include/gtk-3.0",
            "-I",
            "/usr/include/pango-1.0",
            "-I",
            "/usr/include/harfbuzz",
            "-I",
            "/usr/include/cairo",
            "-I",
            "/usr/include/gdk-pixbuf-2.0",
            "-I",
            "/usr/include/atk-1.0",
            "-I",
            "/usr/include/libpeas-1.0",
            "-I",
            "/usr/include/gobject-introspection-1.0",
        ])
        // Finish the builder and generate the bindings.
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");
```

### Actual Results

```
  --- stderr
  /usr/include/budgie-desktop/plugin.h:14:10: error: 'applet-info.h' file not found with <angled> include; use "quotes" instead
  /usr/include/budgie-desktop/plugin.h:15:10: error: 'applet.h' file not found with <angled> include; use "quotes" instead
  /usr/include/budgie-desktop/plugin.h:16:10: error: 'budgie-enums.h' file not found with <angled> include; use "quotes" instead
  /usr/include/budgie-desktop/plugin.h:17:10: error: 'popover-manager.h' file not found with <angled> include; use "quotes" instead
  /usr/include/budgie-desktop/plugin.h:18:10: error: 'popover.h' file not found with <angled> include; use "quotes" instead
  /usr/include/budgie-desktop/plugin.h:14:10: error: 'applet-info.h' file not found with <angled> include; use "quotes" instead, err: true
  /usr/include/budgie-desktop/plugin.h:15:10: error: 'applet.h' file not found with <angled> include; use "quotes" instead, err: true
  /usr/include/budgie-desktop/plugin.h:16:10: error: 'budgie-enums.h' file not found with <angled> include; use "quotes" instead, err: true
  /usr/include/budgie-desktop/plugin.h:17:10: error: 'popover-manager.h' file not found with <angled> include; use "quotes" instead, err: true
  /usr/include/budgie-desktop/plugin.h:18:10: error: 'popover.h' file not found with <angled> include; use "quotes" instead, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:50:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
     1: core::panicking::panic_fmt
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
     2: core::result::unwrap_failed
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
     3: core::result::Result<T,E>::expect
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:975:23
     4: build_script_build::main
               at ./build.rs:19:20
     5: core::ops::function::FnOnce::call_once
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
```

### Expected Results

The bindings for the library.

**Comment by emilio** [comment]
I think you need to use -isystem instead of -I for angled includes to work. Does that help?

**Comment by EbonJaeger** [comment]
That plus adding `-isystem /usr/include/budgie-desktop` seems to have worked. I... think? The bindings contain what looks like all of GLib and GTK. So I guess the next quest is to not have that, if possible xD

**Comment by emilio** [comment]
You can use the allowlist/blocklist APIs to generate just what you want.

**Comment by EbonJaeger** [comment]
Gotcha. Thanks! This can be closed I think.
