### ISSUE TITLE
Unable to find libclang: "the libclang shared library

### ISSUE THREAD

**Issue by hyper-self** [rust-lang/rust-bindgen#2360]
apk info clang-dev
clang15-dev-15.0.5-r0 description:
A C language family front-end for LLVM (development files)

clang15-dev-15.0.5-r0 webpage:
https://llvm.org/

clang15-dev-15.0.5-r0 installed size:
21 MiB

cat /etc/alpine-release
3.15.1

--- stderr
thread 'main' panicked at 'Unable to find libclang: "the libclang shared library at /usr/lib/libclang.so.15.0.5 could not be opened: Dynamic loading not supported"', /root/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/bindgen-0.60.1/src/lib.rs:2172:31

**Comment by pvdrz** [comment]
A similar (but not exactly the same) issue happens here https://github.com/Rust-for-Linux/linux/issues/934 and I suspect it is because the clang-sys version we use does not support clang 15.

We will update the clang-sys version and do a new release as soon as possible.

**Comment by Karrq** [comment]
Hello, I have the same issue but I'm using the latest version of bindgen (tried a couple of older versions too) and clang 12 with alpine 3.15.8
```
Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.12 could not be opened: Dynamic loading not supported
```

**Comment by pvdrz** [comment]
@Karrq have you tried this?

> well this says that dynamic loading is not supported, what happens if you use the `static` feature of bindgen?
> 
> EDIT: the `runtime` feature is enabled by default so you have to disable default features first. See https://docs.rs/crate/bindgen/0.60.1/features

**Comment by Karrq** [comment]
@pvdrz I did, but then this is the error https://github.com/rust-lang/rust-bindgen/issues/2333

**Comment by Karrq** [comment]
I found the root cause: https://github.com/rust-lang/cargo/issues/4423

I'm in a cross-compilation environment, thus `RUSTFLAGS` are ignored. The only sensible workaround (that I found for now) is using the `host-config` unstable feature

**Comment by quadroli** [comment]
How did you all work your way around this ?

**Comment by bnusunny** [comment]
I had the same issue on Alpine Linux 3.20 and found one workaround. Here are the steps:

1. Enable the static feature for bindgen in `Cargo.toml`

```toml
[build-dependencies]
bindgen = { version = "0.70", default-features=false, features = ["logging", "prettyplease", "static"] }
```

2. Create a shell script in you project 

```bash
#!/bin/bash
if [ "$1" = "--libs" ]; then
    /usr/bin/llvm-config "$@" "--link-static"
else
    /usr/bin/llvm-config "$@"
fi
```

And make it executable: `chmod +x /path/to/the/script`

3. Set environment variable `LLVM_CONFIG_PATH` to the shell script created in the step 3. 

```shell
export LLVM_CONFIG_PATH=/path/to/the/script
```

The last 2 steps is to workaround a bug in `clang-sys` [here](https://github.com/KyleMayes/clang-sys/blob/master/build/static.rs#L44). It misses `--link-static` option when using `llvm-config` to list the static libs (.a). Without that option, `llvm-config` gives the dynamic libs (.so).

**Comment by Congyuwang** [comment]
> I had the same issue on Alpine Linux 3.20 and found one workaround. Here are the steps:
> 
> 1. Enable the static feature for bindgen in `Cargo.toml`
> 
> [build-dependencies]
> bindgen = { version = "0.70", default-features=false, features = ["logging", "prettyplease", "static"] }
>  2. Create a shell script in your project
> 
> #!/bin/bash
> if [ "$1" = "--libs" ]; then
>     /usr/bin/llvm-config "$@" "--link-static"
> else
>     /usr/bin/llvm-config "$@"
> fi
> You may need to adjust the ` /usr/bin/llvm-config` path dependending on your system configuration.
> 
> And make it executable: `chmod +x /path/to/the/script`
> 
> 3. Set environment variable `LLVM_CONFIG_PATH` to the shell script created in the step 2.
> 
> export LLVM_CONFIG_PATH=/path/to/the/script
> The last 2 steps is to workaround a bug in `clang-sys` [here](https://github.com/KyleMayes/clang-sys/blob/master/build/static.rs#L44). It misses `--link-static` option when using `llvm-config` to list the static libs (.a). Without that option, `llvm-config` gives the dynamic libs (.so).

I get:

```
  thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clang-sys-1.8.1/build.rs:55:9:
  `runtime` and `static` features can't be combined
```

**Comment by Nohac** [comment]
I also hit this issue, I installed the cli using cargo: `cargo install bindgen-cli`.
I'm getting the following error when running `bindgen`:
```
Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which makes no sense, because those libs are already in my PATH:
```
ldconfig -p | grep libclang
	libclang.so.21.1 (libc6,x86-64) => /usr/lib/libclang.so.21.1
	libclang.so (libc6,x86-64) => /usr/lib/libclang.so
	libclang-cpp.so.21.1 (libc6,x86-64) => /usr/lib/libclang-cpp.so.21.1
	libclang-cpp.so (libc6,x86-64) => /usr/lib/libclang-cpp.so
```
Running with the suggested path variable does fix it:
```
LIBCLANG_PATH=/usr/lib/libclang.so bindgen
```
