### ISSUE TITLE
Error when building bindgen-integration on Apple Silicon

### ISSUE THREAD

**Issue by thomasantony** [rust-lang/rust-bindgen#2444]
I am trying to build the `bindgen-integration` test crate (https://github.com/rust-lang/rust-bindgen/tree/main/bindgen-integration) on an Apple Silicon Mac running macOS Venura 13.2.1 and Rust 1.68.0.

### Actual Results

```
   Compiling bindgen-integration v0.1.0 (/<snip>/rust-bindgen/bindgen-integration)
The following warnings were emitted during compilation:

warning: In file included from cpp/Test.cc:1:
warning: cpp/Test.h:54:37: warning: 'final' keyword is a C++11 extension [-Wc++11-extensions]
warning: class InheritsFromVirtualDestructor final : public VirtualDestructor {
warning:                                     ^
warning: cpp/Test.h:58:36: warning: 'final' keyword is a C++11 extension [-Wc++11-extensions]
warning:   ~InheritsFromVirtualDestructor() final;
warning:                                    ^
warning: cpp/Test.cc:12:66: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
warning: InheritsFromVirtualDestructor::InheritsFromVirtualDestructor() = default;
warning:                                                                  ^
warning: In file included from cpp/Test.cc:1:
warning: cpp/Test.h:32:7: warning: private field 'm_int' is not used [-Wunused-private-field]
warning:   int m_int;
warning:       ^
warning: cpp/Test.h:33:10: warning: private field 'm_double' is not used [-Wunused-private-field]
warning:   double m_double;
warning:          ^
warning: 5 warnings generated.

error: failed to run custom build command for `bindgen-integration v0.1.0 (/<snip>/rust-bindgen/bindgen-integration)`

Caused by:
  process didn't exit successfully: `/<snip>/rust-bindgen/target/debug/build/bindgen-integration-e5e0ca0da97bb388/build-script-build` (signal: 6, SIGABRT: process abort signal)
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CXX_aarch64-apple-darwin
  CXX_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_aarch64_apple_darwin
  CXX_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64-apple-darwin
  CXXFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64_apple_darwin
  CXXFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-o" "/<snip>/rust-bindgen/target/debug/build/bindgen-integration-1ca8af7f7065d108/out/cpp/Test.o" "-c" "cpp/Test.cc"
  cargo:warning=In file included from cpp/Test.cc:1:
  cargo:warning=cpp/Test.h:54:37: warning: 'final' keyword is a C++11 extension [-Wc++11-extensions]
  cargo:warning=class InheritsFromVirtualDestructor final : public VirtualDestructor {
  cargo:warning=                                    ^
  cargo:warning=cpp/Test.h:58:36: warning: 'final' keyword is a C++11 extension [-Wc++11-extensions]
  cargo:warning=  ~InheritsFromVirtualDestructor() final;
  cargo:warning=                                   ^
  cargo:warning=cpp/Test.cc:12:66: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  cargo:warning=InheritsFromVirtualDestructor::InheritsFromVirtualDestructor() = default;
  cargo:warning=                                                                 ^
  cargo:warning=In file included from cpp/Test.cc:1:
  cargo:warning=cpp/Test.h:32:7: warning: private field 'm_int' is not used [-Wunused-private-field]
  cargo:warning=  int m_int;
  cargo:warning=      ^
  cargo:warning=cpp/Test.h:33:10: warning: private field 'm_double' is not used [-Wunused-private-field]
  cargo:warning=  double m_double;
  cargo:warning=         ^
  cargo:warning=5 warnings generated.
  exit status: 0
  cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
  AR_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
  AR_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  running: ZERO_AR_DATE="1" "ar" "cq" "/<snip>/rust-bindgen/target/debug/build/bindgen-integration-1ca8af7f7065d108/out/libtest.a" "/<snip>/rust-bindgen/target/debug/build/bindgen-integration-1ca8af7f7065d108/out/cpp/Test.o"
  exit status: 0
  running: "ar" "s" "/<snip>/rust-bindgen/target/debug/build/bindgen-integration-1ca8af7f7065d108/out/libtest.a"
  exit status: 0
  cargo:rustc-link-lib=static=test
  cargo:rustc-link-search=native=/<snip>/rust-bindgen/target/debug/build/bindgen-integration-1ca8af7f7065d108/out
  cargo:rerun-if-env-changed=CXXSTDLIB_aarch64-apple-darwin
  CXXSTDLIB_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXSTDLIB_aarch64_apple_darwin
  CXXSTDLIB_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXSTDLIB
  HOST_CXXSTDLIB = None
  cargo:rerun-if-env-changed=CXXSTDLIB
  CXXSTDLIB = None
  cargo:rustc-link-lib=c++

  --- stderr
  cpp/Test.h:3:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
  cpp/Test.h:118:19: error: width of bit-field 'ptr' (48 bits) exceeds the size of its type (32 bits)
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `4`,
   right: `8`: "arm64-apple-darwin" "aarch64-apple-darwin"', bindgen/lib.rs:2642:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
     2: core::panicking::assert_failed_inner
     3: core::panicking::assert_failed
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:212:5
     4: bindgen::Bindings::generate
               at /<snip>/rust-bindgen/bindgen/lib.rs:2642:13
     5: bindgen::Builder::generate
               at /<snip>/rust-bindgen/bindgen/lib.rs:1573:9
     6: build_script_build::setup_macro_test
               at ./build.rs:168:20
     7: build_script_build::main
               at ./build.rs:276:5
     8: core::ops::function::FnOnce::call_once
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `0`,
   right: `3`: str_macro handle was not called once for all relevant macros', bindgen-integration/build.rs:139:9
  stack backtrace:
     0:        0x100c028b8 - std::backtrace_rs::backtrace::libunwind::trace::h8787edacd429d828
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x100c028b8 - std::backtrace_rs::backtrace::trace_unsynchronized::h7a9846606490caa8
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x100c028b8 - std::sys_common::backtrace::_print_fmt::h95438bed72312512
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
     3:        0x100c028b8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1027694b54c428d0
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x100c1e770 - core::fmt::write::hb60cc483d75d6594
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
     5:        0x100bff408 - std::io::Write::write_fmt::h6c907fc10bdb865b
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
     6:        0x100c026cc - std::sys_common::backtrace::_print::h323796fb767df5e0
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
     7:        0x100c026cc - std::sys_common::backtrace::print::h1a62458f14dd2797
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
     8:        0x100c04438 - std::panicking::default_hook::{{closure}}::h03c6918072c36210
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
     9:        0x100c04190 - std::panicking::default_hook::hd0f3cf66b6a0fb5e
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
    10:        0x100c04a5c - std::panicking::rust_panic_with_hook::h9ed2a7a45efbd034
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
    11:        0x100c0487c - std::panicking::begin_panic_handler::{{closure}}::h535244d6186e3534
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
    12:        0x100c02d20 - std::sys_common::backtrace::__rust_end_short_backtrace::ha542aa49031c5cb5
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
    13:        0x100c045d8 - rust_begin_unwind
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
    14:        0x100c337a0 - core::panicking::panic_fmt::hc1e7b11add95109d
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
    15:        0x100c33a0c - core::panicking::assert_failed_inner::hb0860579516dd5b5
    16:        0x100c26764 - core::panicking::assert_failed::hea72361393272821
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:212:5
    17:        0x1006afc50 - <build_script_build::MacroCallback as core::ops::drop::Drop>::drop::h349b74da58c24060
                                 at /<snip>/rust-bindgen/bindgen-integration/build.rs:139:9
    18:        0x1006af618 - core::ptr::drop_in_place<build_script_build::MacroCallback>::hce7faa247c063613
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    19:        0x1007198b8 - core::ptr::drop_in_place<dyn bindgen::callbacks::ParseCallbacks>::h9006f111bc746bc8
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    20:        0x10071cb78 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hcc7779788300cb70
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/rc.rs:1593:17
    21:        0x10071bbb0 - core::ptr::drop_in_place<alloc::rc::Rc<dyn bindgen::callbacks::ParseCallbacks>>::h0c267948889f1290
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    22:        0x10071c5bc - core::ptr::drop_in_place<[alloc::rc::Rc<dyn bindgen::callbacks::ParseCallbacks>]>::h1b08cb36a7143f81
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    23:        0x10071d6f8 - <alloc::vec::Vec<T,A> as core::ops::drop::Drop>::drop::h6754e2c8395b6687
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/vec/mod.rs:3059:13
    24:        0x1007122e0 - core::ptr::drop_in_place<alloc::vec::Vec<alloc::rc::Rc<dyn bindgen::callbacks::ParseCallbacks>>>::hbaedb308e813d055
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    25:        0x100716100 - core::ptr::drop_in_place<bindgen::BindgenOptions>::h09f66ffbacffab30
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    26:        0x100718a84 - core::ptr::drop_in_place<bindgen::ir::context::BindgenContext>::hd1d47039f1a15afb
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ptr/mod.rs:490:1
    27:        0x100750310 - bindgen::Bindings::generate::hc8dcc8be768add4a
                                 at /<snip>/rust-bindgen/bindgen/lib.rs:2664:5
    28:        0x10074d9e0 - bindgen::Builder::generate::h7b1921a80d5e224e
                                 at /<snip>/rust-bindgen/bindgen/lib.rs:1573:9
    29:        0x1006b4cac - build_script_build::setup_macro_test::h2f8c9b2cf7873f35
                                 at /<snip>/rust-bindgen/bindgen-integration/build.rs:168:20
    30:        0x1006b5d60 - build_script_build::main::he632b9752ea4bbce
                                 at /<snip>/rust-bindgen/bindgen-integration/build.rs:276:5
    31:        0x1006af020 - core::ops::function::FnOnce::call_once::h81be30b31b868fc6
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
    32:        0x1006aa330 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6940294ecf8c3a19
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:121:18
    33:        0x1006b2ea8 - std::rt::lang_start::{{closure}}::hf997de3cfe46181c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:166:18
    34:        0x100bfb0a8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h602b6f29451c74c7
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:287:13
    35:        0x100bfb0a8 - std::panicking::try::do_call::h8ad76c1527a3892b
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
    36:        0x100bfb0a8 - std::panicking::try::hbfc990f7ac38d34c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
    37:        0x100bfb0a8 - std::panic::catch_unwind::h936bb5789e0b4241
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
    38:        0x100bfb0a8 - std::rt::lang_start_internal::{{closure}}::h896fa40a3ab062d0
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:48
    39:        0x100bfb0a8 - std::panicking::try::do_call::h21fb8583a42bdaac
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
    40:        0x100bfb0a8 - std::panicking::try::h90121103ee57470a
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
    41:        0x100bfb0a8 - std::panic::catch_unwind::hfd5c7b5d06b8f149
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
    42:        0x100bfb0a8 - std::rt::lang_start_internal::h9f0566e553deb11e
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:20
    43:        0x1006b2e74 - std::rt::lang_start::hfd7d68a92457c8ec
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:165:17
    44:        0x1006b5e54 - _main
  thread panicked while panicking. aborting.
```

I get similar errors building some of other crates as well (notably https://github.com/setzer22/llama-rs/ ). However I *am* able to build https://github.com/yue2388253/rust_bindgen_example without problems.

### Expected Results

The `bindgen-integration` crate should build successfully.

**Comment by thomasantony** [comment]
I am building on an M1 mac for an M1 mac, so there is no cross compilation happening. It is using Apple's built-in "clang" compiler (presumably aliased to `c++`). Here is the version information from the compiler:

```
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I also installed llvm using `brew install llvm`. `libclang.dylib` is present in /usr/local/lib

**Comment by pvdrz** [comment]
And what's your `rustup target`?

**Comment by thomasantony** [comment]
`stable-aarch64-apple-darwin`

**Comment by kulp** [comment]
As another data point: I have an M1 Macbook on macOS **12.6.3** and I am able to do this successfully:
```bash
cd `mktemp -d`
git clone https://github.com/rust-lang/rust-bindgen.git .
cd bindgen-integration
cargo build
```

Maybe this is specific to macOS **Ventura**. I have been delaying upgrading my macOS version, but when I do upgrade, I will check to see if I get the same result.

<details>

```
❯ rustc --version
rustc 1.68.0 (2c8cc3432 2023-03-06)
❯ rustup default       
stable-aarch64-apple-darwin (default)
❯ clang --version
Homebrew clang version 15.0.7
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
```
</detail>

**Comment by pvdrz** [comment]
Well I've noticed that @thomasantony also happens to have a lower `clang` version. Not sure if that matters but it is something else to consider

**Comment by thomasantony** [comment]
Interesting. I installed the homebrew version of clang like @kulp and it build fine now. I also upgraded my OS to macOS 13.3 Beta. I guess it was something weird with the built-in clang ?

**Comment by pvdrz** [comment]
Ok so it seems that regardless of the OS version, if you upgrade to clang 15 the problem is gone. Right?

I've seen news about `clang` 15 adding support for `-march=native` on Apple M1. So it might be that `clang` was using a different architecture on back stage and still reporting the "right" target to us.

**Comment by thomasantony** [comment]
That is correct. I guess this can be closed for now?
