### ISSUE TITLE
Can't find system headers

### ISSUE THREAD

**Issue by zRegle** [rust-lang/rust-bindgen#2575]
```bash
cpp/node_manager_client_adapter.h:4:10: fatal error: 'stdbool.h' file not found
thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("cpp/node_manager_client_adapter.h:4:10: fatal error: 'stdbool.h' file not found\n")'
stack backtrace:
     0: rust_begin_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
     2: core::result::unwrap_failed
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Is there any clue to solve this problem? Thx in advance.

Here is the version of dependency: 
**bindgen:** 0.60.1
**rustc:** 1.70.0
**clang:** 14.0.6
**gcc:** 7.3.1

**Comment by pvdrz** [comment]
it depends on what 'stdbool` are you pointing at. Maybe running `find /usr/include/ -name "stdbool.h"` would let you know possible candidates?

**Comment by zRegle** [comment]
> it depends on what `stdbool` are you pointing at. Maybe running `find /usr/include/ -name "stdbool.h"` would let you know possible candidates?

It seems like the root cause is that "Unable to find libclang"
```bash
thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/bindgen-0.60.1/src/lib.rs:2172:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Even though I've already set the environment variable in `~/.bashrc`
```bash
export LIBCLANG_PATH=/usr/local/lib
```

**Comment by pvdrz** [comment]
If `libclang.so` is not at `/usr/local/lib/` then this might be an issue with `clang-sys` as that's what we use to get the libclang bindings (see: https://github.com/KyleMayes/clang-sys#environment-variables).

That being said `LIBCLANG_PATH` can also point to the exact `.so` file you want to use so you might try to run bindgen with the env variable explicitly set in the command.

**Comment by zRegle** [comment]
> If `libclang.so` is not at `/usr/local/lib/` then this might be an issue with `clang-sys` as that's what we use to get the libclang bindings (see: https://github.com/KyleMayes/clang-sys#environment-variables).
> 
> That being said `LIBCLANG_PATH` can also point to the exact `.so` file you want to use, so you might try to run bindgen with the env variable explicitly set in the command, .i.e., `env LIBCLANG_PATH=/usr/lib/libclang.so bindgen ...`

Thank you, I managed to fix this. But the original problem still exists, here is the result of `find /usr/include/ -name "stdbool.h"`
```bash
/usr/include/c++/4.8.2/tr1/stdbool.h
```
Should I change the include path?
