### ISSUE TITLE
Bindgen 66.1: panic - FromBytesWithNulError { kind: InteriorNul(1) }

### ISSUE THREAD

**Issue by MolotovCherry** [rust-lang/rust-bindgen#2620]
With the following headers on windows, this panic happens when building (see below report).

For a full repo example, please see my repo crate `wdf-umdf-sys` [here](https://github.com/MolotovCherry/virtual-display-rs/tree/master/wdf-umdf-sys). Set the version back to `66.1` since I've pushed a version downgrade to master.

For the example to build, you need the windows sdk with desktop c++ installed, along with build tools for visual studio. You also need to install the Windows WDK.

_These builds perfectly fine on 65.1, it only panics on 66.1_

For others reading this, current workaround is to downgrade to 65.1

Possibly related: #2610 

### Input C/C++ Header

```C++
#define AMD64
#define _AMD64_

#include <Windows.h>

#define WDF_STUB

#include <wdf.h>

#define IDD_STUB

#include <iddcx\1.9\IddCx.h>
```

### Bindgen Invocation

```Rust
    let umdf = bindgen::Builder::default()
        .derive_debug(false)
        .layout_tests(false)
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        //.merge_extern_blocks(true)
        .header("c/wrapper.h")
        // general um includes
        .clang_arg(format!("-I{}", include_um_dir.display()))
        // umdf includes
        .clang_arg(format!("-I{}", wdf_include_dir.display()))
        .clang_arg(format!("-I{}", shared.display()))
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .blocklist_type("_?P?IMAGE_TLS_DIRECTORY.*")
        // we will use our own custom type
        .blocklist_item("NTSTATUS")
        .clang_arg("--language=c++")
        // generate
        .generate()
        .unwrap();
```

### Actual Results

```rs
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromBytesWithNulError { kind: InteriorNul(1) }', C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:717:71
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
     1: core::panicking::panic_fmt
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
     2: core::result::unwrap_failed
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\result.rs:1651
     3: enum2$<core::result::Result<ref$<core::ffi::c_str::CStr>,core::ffi::c_str::FromBytesWithNulError> >::unwrap<ref$<core::ffi::c_str::CStr>,core::ffi::c_str::FromBytesWithNulError>
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\result.rs:1076
     4: bindgen::codegen::impl$11::codegen
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:717
     5: bindgen::codegen::impl$9::codegen
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:540
     6: bindgen::codegen::impl$10::codegen::closure$0
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:566
     7: bindgen::codegen::impl$10::codegen
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:596
     8: bindgen::codegen::impl$9::codegen
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:534
     9: bindgen::codegen::codegen::closure$0
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:4719
    10: bindgen::ir::context::BindgenContext::gen<bindgen::codegen::codegen::closure_env$0,proc_macro2::TokenStream>
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\ir\context.rs:1218
    11: bindgen::codegen::codegen
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\codegen\mod.rs:4683
    12: bindgen::Bindings::generate
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\lib.rs:896
    13: bindgen::Builder::generate
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.66.1\lib.rs:338
    14: build_script_build::generate
               at .\build.rs:148
    15: build_script_build::main
               at .\build.rs:178
    16: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected Results

Generation to succeed

**Comment by MolotovCherry** [comment]
This is fixed in 68.1. It can be closed
