### ISSUE TITLE
Auto-generated unit tests fail

### ISSUE THREAD

**Issue by zrneely** [rust-lang/rust-bindgen#649]
bindgen 0.23.1's automatically generated unit tests fail when generating bindings to `libmediainfo` (available on Debian systems as `libmediainfo-dev`).

### Input C/C++ Header

```C++
#include <MediaInfo/MediaInfo.h>
```

#### build.rs
```Rust
 bindgen::builder()
      .header("mediainfo_wrapper.h")
      .no_unstable_rust()
      .enable_cxx_namespaces()
      .whitelisted_type("MediaInfoLib::MediaInfo")
      .clang_args(&["-x", "c++"])
      .generate()
      .unwrap()
      .write_to_file(Path::new(&out_dir).join("libmediainfo_autogen.rs"))
      .unwrap();
 println!("cargo:rustc-link-lib=mediainfo");
```
#### src/lib.rs
```Rust
include!(concat!(env!("OUT_DIR"), "/libmediainfo_autogen.rs"));
```

### Actual Results

```
$ RUST_BACKTRACE=1 cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.2 secs
     Running target/debug/deps/bindgen_err-5f7c70890ae8178f

running 7 tests
test root::MediaInfoLib::bindgen_test_layout_MediaInfo ... ok
test root::bindgen_test_layout___mbstate_t__bindgen_ty_1 ... ok
test root::bindgen_test_layout___mbstate_t ... ok
test root::std::__bindgen_test_layout_allocator_instantiation_5638 ... ok
test root::std::__bindgen_test_layout_char_traits_instantiation_3775 ... ok
test tests::it_works ... ok
test root::std::__bindgen_test_layout_basic_string_instantiation_8491 ... FAILED

failures:

---- root::std::__bindgen_test_layout_basic_string_instantiation_8491 stdout ----
        thread 'root::std::__bindgen_test_layout_basic_string_instantiation_8491' panicked at 'assertion failed: `(left == right)` (left: `16`, right: `32`): Size of template specialization: root :: std :: basic_string < :: std :: os :: raw :: c_char >', /home/zrneely/src/bindgen_err/target/debug/build/bindgen_err-1293e3297a466ae7/out/libmediainfo_autogen.rs:179
stack backtrace:
   1:     0x7f072344e15c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f07234512ae - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f0723450e53 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7f072345174b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f07234515e4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f0723451509 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7f072340fbd9 - bindgen_err::root::std::__bindgen_test_layout_basic_string_instantiation_8491::h2544df62c22c3256
                        at /home/zrneely/src/bindgen_err/src/lib.rs:2
   8:     0x7f072341f95e - <F as test::FnBox<T>>::call_box::he0ddef732487ab41
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:1366
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:140
   9:     0x7f072345865a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  10:     0x7f0723413d4a - std::panicking::try::do_call::h4652d5e10f648844
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:1311
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:460
  11:     0x7f072345865a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  12:     0x7f072341a976 - <F as alloc::boxed::FnBox<A>>::call_box::h274e3783c3771bc8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:614
  13:     0x7f07234505b4 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  14:     0x7f07229c76b9 - start_thread
  15:     0x7f07224d682c - clone
  16:                0x0 - <unknown>


failures:
    root::std::__bindgen_test_layout_basic_string_instantiation_8491

test result: FAILED. 6 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

The bindings appear correct to my eyes, although I'm not an expert.

### Expected Results

The unit tests succeed.

**Comment by fitzgen** [comment]
Hi @zrneely Thanks for the bug report! Sorry for the radio silence, I guess this one slipped through the cracks.

What would really go a long ways towards helping fix this bug would be a [reduced test case](https://github.com/servo/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases) since not all machines have the same headers, and even when they do, their contents can differ drastically.

Thanks!

**Comment by zrneely** [comment]
Hmm, I'll see what I can do, although I've long since switched to manually-written bindings that I haven't touched since shortly after I submitted the issue (it turns out I only needed 5 or 6 functions, and no structs).

**Comment by Vurich** [comment]
So I'm getting similar issues while trying to write bindings for [`Clipper`](http://www.angusj.com/delphi/clipper.php). The issue seems to be that the 3 pointers in `std::vector` are [`u8` instead of `usize`](https://github.com/Vurich/clipper-rs/blob/master/clipper-sys/src/bindings.rs#L394-L398), although I can't be certain that this is what's causing the problem.

**Comment by amanjeev** [comment]
Triaging this one - is it possible for you to create a [reduced test case](https://github.com/servo/rust-bindgen/blob/master/CONTRIBUTING.md#using-creduce-to-minimize-test-cases) as pointed by @fitzgen in [the comment above](https://github.com/rust-lang/rust-bindgen/issues/649#issuecomment-317067147)? It will really help us work on this issue.

**Comment by pvdrz** [comment]
Closed due to lack of a reduced case
