### ISSUE TITLE
Quoting arguments on Windows is broken

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust-bindgen#658]
I'm using Windows 10, with the Windows SDK installed and Visual C++ 2017. I run bindgen command

    >bindgen "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winusb.h" -- -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared"

I've tried some other quoting combinations: `"-IC:\..."` and `-I"C:\..."` but it seems like it never handles the spaces correctly. This is the output:

```
warning: Files: 'linker' input unused [-Wunused-command-line-argument]
warning: (x86)\Windows: 'linker' input unused [-Wunused-command-line-argument]
warning: Kits\10\Include\10.0.14393.0\shared: 'linker' input unused [-Wunused-command-line-argument]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winusb.h:38:10: fatal error: 'winapifamily.h' file not found
warning: Files: 'linker' input unused [-Wunused-command-line-argument], err: false
warning: (x86)\Windows: 'linker' input unused [-Wunused-command-line-argument], err: false
warning: Kits\10\Include\10.0.14393.0\shared: 'linker' input unused [-Wunused-command-line-argument], err: false
C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winusb.h:38:10: fatal error: 'winapifamily.h' file not found, err: true
```

As you can see the include directories have been split up by their spaces.

**Comment by emilio** [comment]
I don't have any window machine to test this one, but I'm skeptic this is a bindgen problem. We use [`clap`](https://crates.io/crates/clap) to parse CLI arguments, maybe other applications using it have the same problem?

**Comment by chris3k** [comment]
I leave my comment here, because I think this might be related.

Bindgen is unable to find libclang.dll under windows 8.1.

```
c:\user\proj\rust-bindgen\target\debug>set RUST_BACKTRACE=1

c:\user\proj\rust-bindgen\target\debug>.\bindgen.exe
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library could not be opened: C:\\Program Files (x86)\\LLVM\\bin\\libclang.dll"', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<collections::string::String>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<(), collections::string::String>::expect<(),collections::string::String>
             at C:\projects\rust\src\libcore\result.rs:761
  10: bindgen::clang_version
             at C:\user\proj\rust-bindgen\src\lib.rs:1229
  11: bindgen::main
             at C:\user\proj\rust-bindgen\src\main.rs:33
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  16: BaseThreadInitThunk
```
```
c:\user\proj\rust-bindgen\target\debug>dir "c:\Program Files (x86)\LLVM\bin\"
 Volume in drive C has no label.

 Directory of c:\Program Files (x86)\LLVM\bin

2017-05-05  22:53    <DIR>          .
2017-05-05  22:53    <DIR>          ..
2017-03-09  19:50        63 566 848 clang++.exe
2017-03-09  19:35         2 357 248 clang-apply-replacements.exe
2017-03-09  19:37        17 489 408 clang-change-namespace.exe
2017-03-09  19:35        52 584 448 clang-check.exe
2017-03-09  19:50        63 566 848 clang-cl.exe
2017-03-09  19:50        63 566 848 clang-cpp.exe
2017-03-09  19:35         2 380 800 clang-format.exe
2017-03-09  19:35        20 820 480 clang-import-test.exe
2017-03-09  19:37        17 238 528 clang-include-fixer.exe
2017-03-09  19:34         3 140 096 clang-offload-bundler.exe
2017-03-09  19:37        17 924 608 clang-query.exe
2017-03-09  19:35        17 438 208 clang-rename.exe
2017-03-09  19:35        17 171 456 clang-reorder-fields.exe
2017-03-09  19:37        22 490 624 clang-tidy.exe
2017-03-09  19:35        63 566 848 clang.exe
2017-03-09  19:37        17 251 840 find-all-symbols.exe
2016-11-08  07:50            20 626 git-clang-format
2017-03-09  19:50        44 386 816 ld.lld.exe
2017-03-09  19:38        55 871 488 libclang.dll
2017-03-09  19:50           574 976 libiomp5md.dll
2017-03-09  19:29           574 976 libomp.dll
2017-03-09  19:50        44 386 816 lld-link.exe
2017-03-09  19:37        44 386 816 lld.exe
2017-03-09  19:30        14 962 688 llvm-ar.exe
2017-03-09  19:50        14 962 688 llvm-lib.exe
2017-03-09  19:37        15 513 600 llvm-objdump.exe
2017-03-09  19:50        14 962 688 llvm-ranlib.exe
2017-03-09  19:30        42 117 120 LTO.dll
2017-03-09  19:35        16 766 976 modularize.exe
2015-11-13  22:34                23 scan-build.bat
2015-12-21  14:19             4 504 scan-view
              31 File(s)    772 047 937 bytes
               2 Dir(s)  15 011 840 000 bytes free
```

And do not respect `LIBCLANG_PATH` environment variable

```
c:\user\proj\rust-bindgen\target\debug>set LIBCLANG_PATH="c:\Program Files (x86)\LLVM\bin\"

c:\user\proj\rust-bindgen\target\debug>.\bindgen.exe
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library could not be opened: C:\\Program Files (x86)\\LLVM\\bin\\libclang.dll"', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<collections::string::String>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<(), collections::string::String>::expect<(),collections::string::String>
             at C:\projects\rust\src\libcore\result.rs:761
  10: bindgen::clang_version
             at C:\user\proj\rust-bindgen\src\lib.rs:1229
  11: bindgen::main
             at C:\user\proj\rust-bindgen\src\main.rs:33
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  16: BaseThreadInitThunk
```

```
c:\user\proj\rust-bindgen\target\debug>set LIBCLANG_PATH="c:\user\proj\rust-bindgen\"

c:\user\proj\rust-bindgen\target\debug>.\bindgen.exe
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library could not be opened: C:\\Program Files (x86)\\LLVM\\bin\\libclang.dll"', src\libcore\result.rs:85
9
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<collections::string::String>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<(), collections::string::String>::expect<(),collections::string::String>
             at C:\projects\rust\src\libcore\result.rs:761
  10: bindgen::clang_version
             at C:\user\proj\rust-bindgen\src\lib.rs:1229
  11: bindgen::main
             at C:\user\proj\rust-bindgen\src\main.rs:33
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  16: BaseThreadInitThunk
```

**Comment by emilio** [comment]
cc @KyleMayes (I know you're busy, but just in case this rings any bells)

I don't have a windows machine, if someone that does could step with a debugger into [`clang-sys`](https://github.com/kylemayes/clang-sys) and see what's going on, that'd be rad :)

**Comment by chris3k** [comment]
Ok, in my case issue was unmatched build target, I used 32-bit clang and 64-bit bindgen.

**Comment by fitzgen** [comment]
So did we come to a resolution here? Is there still a bug? It isn't clear to me.

**Comment by emilio** [comment]
This doesn't look like a bug per the last few comments, but please reopen if I misunderstood.

**Comment by weiby3** [comment]
It seems this problem is still exist in latest version.
I try 0.51.0, and got 
```
$ LIBCLANG_PATH=/tmp cargo run
(.........)
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at C:/msys64/tmp\\libclang.dll could not be opened: 找不到指定的程序。 (os error 127)"', src\libcore\result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
but the libclang.dll exist
```
$ ll /tmp/libclang.dll
-rwxr-xr-x 1 Administrator None 80M 八月    7 14:47 /tmp/libclang.dll*
```
So is there any progress?

**Comment by emilio** [comment]
LIBCLANG_PATH handling is not bindgen's business, that's different from what was reported here.

That looks like a bug in `clang-sys`: https://github.com/kylemayes/clang-sys
